package hiddenknight5.worldevents;
import java.util.*;
import org.bukkit.*; import org.bukkit.block.*; import org.bukkit.command.*; import org.bukkit.entity.*; import org.bukkit.event.*; import org.bukkit.event.block.BlockPlaceEvent; import org.bukkit.inventory.*; import org.bukkit.plugin.java.JavaPlugin; import org.bukkit.potion.*;
public class WorldEventsPlugin extends JavaPlugin implements CommandExecutor,Listener{
 Random r=new Random(); String active; BukkitTask task,randomTask; Map<String,List<String>> clues=new HashMap<String,List<String>>(); Map<String,Location> finals=new HashMap<String,Location>();
 public void onEnable(){saveDefaultConfig();getCommand("event").setExecutor(this);getServer().getPluginManager().registerEvents(this,this);nextRandom();getLogger().info("WorldEvents 1.0.0 enabled.");}
 public void onDisable(){cancel();if(randomTask!=null)randomTask.cancel();}
 void msg(CommandSender s,String x){s.sendMessage(ChatColor.translateAlternateColorCodes('&',getConfig().getString("messages.prefix","&8[&5WorldEvents&8] ")+x));}
 void bc(String x){Bukkit.broadcastMessage(ChatColor.translateAlternateColorCodes('&',getConfig().getString("messages.prefix","&8[&5WorldEvents&8] ")+x));}
 void nextRandom(){if(randomTask!=null)randomTask.cancel();if(!getConfig().getBoolean("random-events.enabled",true))return;int a=Math.max(1,getConfig().getInt("random-events.minimum-days",1)),b=Math.max(a,getConfig().getInt("random-events.maximum-days",10));long t=(long)(a+r.nextInt(b-a+1))*24000L;randomTask=Bukkit.getScheduler().runTaskLater(this,new Runnable(){public void run(){if(active==null||getConfig().getBoolean("random-events.allow-while-event-active",false))weighted();else nextRandom();}},t);}
 void weighted(){String[] n={"bloodmoon","purge","meteor_shower","supply_drop","zombie_outbreak","boss_attack","eclipse","abandoned_structure","treasure_hunt","inferno","unknown_signal"};int total=0;for(String x:n)total+=Math.max(0,getConfig().getInt("random-event-weights."+x,1));int q=r.nextInt(Math.max(1,total));for(String x:n){q-=Math.max(0,getConfig().getInt("random-event-weights."+x,1));if(q<0){start(x);return;}}}
 void cancel(){if(task!=null)task.cancel();task=null;active=null;}
 void endIn(final String n,long t){if(task!=null)task.cancel();task=Bukkit.getScheduler().runTaskLater(this,new Runnable(){public void run(){if(n.equals(active)){bc("&aThe "+n+" event has ended.");cancel();nextRandom();}}},t);}
 Player p(){for(Player x:Bukkit.getOnlinePlayers())return x;return null;}
 Location near(Player p,double rad){World w=p.getWorld();for(int i=0;i<30;i++){double a=r.nextDouble()*6.283,d=20+r.nextDouble()*rad;int x=(int)(p.getLocation().getX()+Math.cos(a)*d),z=(int)(p.getLocation().getZ()+Math.sin(a)*d),y=w.getHighestBlockYAt(x,z);Material m=w.getBlockAt(x,y,z).getType();if(y>1&&m!=Material.WATER&&m!=Material.LAVA&&m!=Material.STATIONARY_WATER&&m!=Material.STATIONARY_LAVA)return new Location(w,x+.5,y+1,z+.5);}return p.getLocation();}
 void chest(Location l,boolean rare){l.getBlock().setType(Material.CHEST);Inventory i=((Chest)l.getBlock().getState()).getInventory();i.addItem(new ItemStack(Material.DIAMOND,2+r.nextInt(5)),new ItemStack(Material.GOLDEN_APPLE,1+r.nextInt(2)));if(rare){i.addItem(new ItemStack(Material.SKULL_ITEM,1));if(r.nextInt(4)==0)i.addItem(new ItemStack(Material.ELYTRA));}else if(r.nextInt(5)==0)i.addItem(new ItemStack(Material.ELYTRA));}
 void start(String n){cancel();active=n;bc("&dAn event has begun: &5"+n.replace('_',' '));if(n.equals("bloodmoon")){for(World w:Bukkit.getWorlds())w.setTime(13000);endIn(n,10000);}else if(n.equals("purge"))endIn(n,getConfig().getLong("events.purge.duration-minutes",10)*1200);else if(n.equals("meteor_shower"))meteors();else if(n.equals("supply_drop"))drop();else if(n.equals("zombie_outbreak"))outbreak();else if(n.equals("boss_attack"))boss();else if(n.equals("eclipse")){for(World w:Bukkit.getWorlds())w.setTime(13000);endIn(n,getConfig().getLong("events.eclipse.duration-minecraft-days",1)*24000);}else if(n.equals("abandoned_structure"))ruin();else if(n.equals("treasure_hunt"))treasure();else if(n.equals("inferno"))inferno();else signal();}
 void meteors(){final int c=Math.max(1,getConfig().getInt("events.meteor-shower.meteors",12));final double rad=getConfig().getDouble("events.meteor-shower.radius",120),pow=getConfig().getDouble("events.meteor-shower.explosion-power",2);task=Bukkit.getScheduler().runTaskTimer(this,new Runnable(){int left=c;public void run(){if(left--<=0){cancel();nextRandom();return;}Player p=p();if(p!=null){Location l=near(p,rad);l.getWorld().strikeLightningEffect(l);l.getWorld().createExplosion(l,pow,false);}}},0,30);}
 void drop(){Player p=p();if(p==null){cancel();return;}chest(near(p,getConfig().getDouble("events.supply-drop.radius",300)),false);bc("&eA supply drop has fallen somewhere in the wilderness.");endIn(active,20);}
 void outbreak(){final long days=Math.max(1,getConfig().getLong("events.zombie-outbreak.duration-minecraft-days",1));task=Bukkit.getScheduler().runTaskTimer(this,new Runnable(){public void run(){for(Player p:Bukkit.getOnlinePlayers())for(int i=0;i<3;i++){Zombie z=(Zombie)p.getWorld().spawnEntity(p.getLocation().clone().add(r.nextInt(17)-8,0,r.nextInt(17)-8),EntityType.ZOMBIE);z.setCustomName(ChatColor.DARK_RED+"Outbreak Zombie");z.addPotionEffect(new PotionEffect(PotionEffectType.SPEED,1200,1));}}},0,200);Bukkit.getScheduler().runTaskLater(this,new Runnable(){public void run(){cancel();bc("&aThe zombie outbreak has ended.");nextRandom();}},days*24000);}
 void boss(){Player p=p();if(p==null){cancel();return;}Zombie z=(Zombie)p.getWorld().spawnEntity(p.getLocation().clone().add(3,0,3),EntityType.ZOMBIE);z.setCustomName(ChatColor.DARK_RED+"THE WARDEN OF ASH");z.setCustomNameVisible(true);z.setMaxHealth(getConfig().getDouble("events.boss-attack.health",150));z.setHealth(z.getMaxHealth());z.addPotionEffect(new PotionEffect(PotionEffectType.SPEED,12000,1));z.addPotionEffect(new PotionEffect(PotionEffectType.INCREASE_DAMAGE,12000,1));z.getEquipment().setHelmet(new ItemStack(Material.DIAMOND_HELMET));z.getEquipment().setChestplate(new ItemStack(Material.DIAMOND_CHESTPLATE));z.getEquipment().setLeggings(new ItemStack(Material.DIAMOND_LEGGINGS));z.getEquipment().setBoots(new ItemStack(Material.DIAMOND_BOOTS));z.getEquipment().setItemInHand(new ItemStack(Material.DIAMOND_SWORD));endIn(active,12000);}
 void ruin(){Player p=p();if(p==null){cancel();return;}Location l=near(p,getConfig().getDouble("events.abandoned-structure.radius",500));for(int x=-2;x<=2;x++)for(int z=-2;z<=2;z++)for(int y=0;y<3;y++)if(Math.abs(x)==2||Math.abs(z)==2)l.getWorld().getBlockAt(l.getBlockX()+x,l.getBlockY()+y,l.getBlockZ()+z).setType(Material.MOSSY_COBBLESTONE);chest(l,false);bc("&7Something abandoned has been discovered in the wilderness.");endIn(active,20);}
 void treasure(){Player p=p();if(p==null){cancel();return;}Location l=near(p,getConfig().getDouble("events.treasure-hunt.radius",1000));chest(l,true);bc("&6A mysterious treasure hunt has begun. &e"+clue(l));endIn(active,20);}
 String clue(Location l){Biome b=l.getBlock().getBiome();if(b==Biome.DESERT)return"The sands hide what was forgotten.";if(b==Biome.JUNGLE)return"Where green giants crowd the sky, something waits.";if(b==Biome.TAIGA)return"Cold forests keep old secrets.";return"The land itself seems to point toward something lost.";}
 void inferno(){final int rr=getConfig().getInt("events.inferno.fire-radius",35);task=Bukkit.getScheduler().runTaskTimer(this,new Runnable(){public void run(){for(Player p:Bukkit.getOnlinePlayers()){Location c=p.getLocation();for(int i=0;i<8;i++){int x=c.getBlockX()+r.nextInt(rr*2+1)-rr,z=c.getBlockZ()+r.nextInt(rr*2+1)-rr,y=c.getWorld().getHighestBlockYAt(x,z);Block b=c.getWorld().getBlockAt(x,y,z);if(b.getType()==Material.AIR)b.setType(Material.FIRE);}}}},0,40);endIn(active,getConfig().getLong("events.inferno.duration-minutes",8)*1200);}
 void signal(){for(Player p:Bukkit.getOnlinePlayers())p.sendMessage(ChatColor.DARK_PURPLE+"[Unknown Signal] "+ChatColor.GRAY+"...we can see you...");endIn(active,200);}
 @EventHandler public void trigger(BlockPlaceEvent e){Location l=e.getBlock().getLocation();World w=l.getWorld();int x=l.getBlockX(),y=l.getBlockY(),z=l.getBlockZ();if(e.getBlock().getType()==Material.FIRE&&w.getBlockAt(x,y-1,z).getType()==Material.NETHERRACK){int g=0;for(int dx=-2;dx<=2;dx++)for(int dz=-2;dz<=2;dz++)if(Math.abs(dx)+Math.abs(dz)==2&&w.getBlockAt(x+dx,y-1,z+dz).getType()==Material.GOLD_BLOCK)g++;if(g>=2){Zombie h=(Zombie)w.spawnEntity(l.clone().add(.5,0,.5),EntityType.ZOMBIE);h.setCustomName(ChatColor.RED+"HEROBRINE");h.setCustomNameVisible(true);h.setMaxHealth(200);h.setHealth(200);h.addPotionEffect(new PotionEffect(PotionEffectType.SPEED,24000,2));h.addPotionEffect(new PotionEffect(PotionEffectType.INCREASE_DAMAGE,24000,1));h.getEquipment().setHelmet(new ItemStack(Material.GOLD_BLOCK));bc("&4HEROBRINE has been summoned.");}}}
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!s.hasPermission("worldevents.admin")){msg(s,"&cYou do not have permission.");return true;}if(a.length==0){msg(s,"&e/event list &7| &e/event status &7| &e/event start <event> &7| &e/event stop &7| &e/event random <on/off> &7| &e/event reload");return true;}String q=a[0].toLowerCase();if(q.equals("list")){msg(s,"&eEvents: bloodmoon, purge, meteor_shower, supply_drop, zombie_outbreak, boss_attack, eclipse, abandoned_structure, treasure_hunt, inferno, unknown_signal");return true;}if(q.equals("status")){msg(s,active==null?"&aNo event active.":"&cActive: &e"+active);return true;}if(q.equals("start")&&a.length>1){start(a[1].toLowerCase());return true;}if(q.equals("stop")){cancel();bc("&cThe current event was stopped.");nextRandom();return true;}if(q.equals("random")&&a.length>1){getConfig().set("random-events.enabled",a[1].equalsIgnoreCase("on"));saveConfig();nextRandom();return true;}if(q.equals("reload")){reloadConfig();nextRandom();msg(s,"&aWorldEvents config reloaded.");return true;}if(q.equals("treasure")&&a.length>2){String n=a[2].toLowerCase();if(a[1].equalsIgnoreCase("create")){clues.put(n,new ArrayList<String>());msg(s,"&aCreated.");return true;}if(a[1].equalsIgnoreCase("clue")&&a.length>3){if(!clues.containsKey(n))clues.put(n,new ArrayList<String>());clues.get(n).add(join(a,3));msg(s,"&aClue added.");return true;}if(a[1].equalsIgnoreCase("setfinal")&&s instanceof Player){finals.put(n,((Player)s).getLocation().clone());msg(s,"&aFinal location saved.");return true;}if(a[1].equalsIgnoreCase("delete")){clues.remove(n);finals.remove(n);msg(s,"&aDeleted.");return true;}if(a[1].equalsIgnoreCase("start")){if(!finals.containsKey(n)){msg(s,"&cSet a final location first.");return true;}Location loc=finals.get(n);chest(loc,true);for(String z:clues.get(n))bc("&6[Treasure Hunt] &e"+z);bc("&6The hunt's final secret is waiting somewhere.");return true;}}return true;}
 String join(String[] a,int f){StringBuilder b=new StringBuilder();for(int i=f;i<a.length;i++){if(i>f)b.append(i==f?"":" ").append(a[i]);}return b.toString();}
}